# Generated by Django 2.1.1 on 2019-03-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o_order',
            name='o_status',
            field=models.IntegerField(default=0, max_length=32),
        ),
    ]
