# Generated by Django 2.1.1 on 2019-01-19 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_jieji',
            name='o_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='order.o_order'),
        ),
        migrations.AddField(
            model_name='o_songji',
            name='o_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='order.o_order'),
        ),
        migrations.AddField(
            model_name='o_tourist',
            name='o_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='order.o_order'),
        ),
    ]
