# Generated by Django 2.1.1 on 2019-03-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190303_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o_order',
            name='o_fukuan',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='o_order',
            name='o_shoukuan',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='o_order',
            name='o_shouli',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='o_order',
            name='o_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='o_order',
            name='o_tijiao',
            field=models.CharField(default='', max_length=128),
        ),
    ]
