# Generated by Django 2.1.1 on 2019-01-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190119_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='o_songji',
            old_name='from_to',
            new_name='o_from',
        ),
        migrations.AddField(
            model_name='o_songji',
            name='o_to',
            field=models.CharField(default='guangzhou', max_length=128),
            preserve_default=False,
        ),
    ]
