# Generated by Django 2.1.1 on 2019-03-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190303_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_order',
            name='o_shoukuan_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='o_order',
            name='o_tijiao_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='o_order',
            name='o_fukuan',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='o_order',
            name='o_shoukuan',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='o_order',
            name='o_shouli',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='o_order',
            name='o_tijiao',
            field=models.CharField(max_length=128),
        ),
    ]
