# Generated by Django 2.1.5 on 2019-01-30 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190119_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o_jieji',
            name='o_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.o_order'),
        ),
        migrations.AlterField(
            model_name='o_order',
            name='o_dahui_msg',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='o_songji',
            name='o_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.o_order'),
        ),
        migrations.AlterField(
            model_name='o_tourist',
            name='o_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.o_order'),
        ),
    ]
