# Generated by Django 2.1.1 on 2019-03-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190303_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o_order',
            name='o_jiesuan_type',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
