# Generated by Django 2.1.5 on 2019-01-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190130_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='o_order',
            name='o_status',
            field=models.CharField(default='暂存', max_length=32),
        ),
        migrations.AlterField(
            model_name='o_order',
            name='remark',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
