# Generated by Django 2.1.1 on 2019-03-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190303_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o_order',
            name='o_tijiao',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
