# Generated by Django 2.1.1 on 2019-03-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190303_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='o_order',
            old_name='o_time',
            new_name='o_zhidan_time',
        ),
        migrations.AlterField(
            model_name='o_order',
            name='o_dahui_msg',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
