# Generated by Django 2.1.1 on 2018-09-15 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Application_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('agency_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acct.Agency_t')),
            ],
        ),
        migrations.CreateModel(
            name='Line_Price_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('remark', models.CharField(blank=True, max_length=128)),
                ('detail', models.TextField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Price_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('kind', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('line_price_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acct.Line_Price_t')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('kind', models.CharField(max_length=64)),
                ('application_t', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='acct.Application_t')),
                ('pay_agency_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acct.Agency_t')),
                ('rec_agency_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rec_agency', to='acct.Agency_t')),
            ],
        ),
        migrations.CreateModel(
            name='Tourist_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('amount', models.IntegerField(default=1)),
                ('fix_price', models.FloatField(default=0)),
                ('final_price', models.FloatField(default=0)),
                ('fix_remark', models.CharField(blank=True, max_length=128)),
                ('trans_price', models.FloatField(default=0)),
                ('trans_remark', models.CharField(blank=True, max_length=128)),
                ('trans_agency', models.CharField(default='0', max_length=128)),
                ('agent_price', models.FloatField(default=0)),
                ('agent_remark', models.CharField(blank=True, max_length=128)),
                ('application_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acct.Application_t')),
                ('ref_price_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acct.Ref_Price_t')),
            ],
        ),
        migrations.AddField(
            model_name='application_t',
            name='def_price_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acct.Ref_Price_t'),
        ),
        migrations.AddField(
            model_name='application_t',
            name='line_name_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acct.Line_Price_t'),
        ),
        migrations.AddField(
            model_name='application_t',
            name='local_agency_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='local', to='acct.Agency_t'),
        ),
    ]
