# Generated by Django 2.1.1 on 2018-10-04 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement_t',
            name='localname',
        ),
    ]
