# Generated by Django 2.1.1 on 2018-10-04 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0002_remove_settlement_t_localname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency_t',
            name='localname',
        ),
        migrations.RemoveField(
            model_name='application_t',
            name='localname',
        ),
        migrations.RemoveField(
            model_name='line_price_t',
            name='localname',
        ),
        migrations.RemoveField(
            model_name='ref_price_t',
            name='localname',
        ),
        migrations.RemoveField(
            model_name='tourist_t',
            name='localname',
        ),
    ]
