# Generated by Django 2.1.1 on 2018-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0004_auto_20181004_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjUser_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('token', models.CharField(default='', max_length=1024)),
                ('is_active', models.BooleanField(default=False)),
                ('local_name', models.CharField(default='system user', max_length=128)),
                ('nick_name', models.CharField(default='nick name', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='application_t',
            name='status',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
