# Generated by Django 2.1.1 on 2018-10-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0005_auto_20181006_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency_t',
            old_name='localname',
            new_name='local_name',
        ),
        migrations.RenameField(
            model_name='application_t',
            old_name='localname',
            new_name='local_name',
        ),
        migrations.RenameField(
            model_name='line_price_t',
            old_name='localname',
            new_name='local_name',
        ),
        migrations.RenameField(
            model_name='ref_price_t',
            old_name='localname',
            new_name='local_name',
        ),
        migrations.RenameField(
            model_name='settlement_t',
            old_name='localname',
            new_name='local_name',
        ),
        migrations.RenameField(
            model_name='tourist_t',
            old_name='localname',
            new_name='local_name',
        ),
        migrations.AddField(
            model_name='djuser_t',
            name='e_mail',
            field=models.EmailField(default='dj@dj.com.cn', max_length=254),
        ),
    ]
