# Generated by Django 2.1.1 on 2018-10-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0006_auto_20181006_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djuser_t',
            old_name='is_active',
            new_name='is_logged',
        ),
    ]
