# Generated by Django 2.1.1 on 2018-10-20 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0008_auto_20181013_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency_t',
            name='local_name',
        ),
        migrations.RemoveField(
            model_name='application_t',
            name='local_name',
        ),
        migrations.RemoveField(
            model_name='djuser_t',
            name='local_name',
        ),
        migrations.RemoveField(
            model_name='line_price_t',
            name='local_name',
        ),
        migrations.RemoveField(
            model_name='ref_price_t',
            name='local_name',
        ),
        migrations.RemoveField(
            model_name='settlement_t',
            name='local_name',
        ),
        migrations.RemoveField(
            model_name='tourist_t',
            name='local_name',
        ),
        migrations.AddField(
            model_name='agency_t',
            name='local_agency_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='acct.Agency_t'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='djuser_t',
            name='local_agency_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='acct.Agency_t'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line_price_t',
            name='local_agency_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='acct.Agency_t'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ref_price_t',
            name='local_agency_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='acct.Agency_t'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settlement_t',
            name='local_agency_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='acct.Agency_t'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourist_t',
            name='local_agency_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='acct.Agency_t'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application_t',
            name='agency_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acct.Agency_t'),
        ),
        migrations.AlterField(
            model_name='application_t',
            name='def_price_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acct.Ref_Price_t'),
        ),
        migrations.AlterField(
            model_name='application_t',
            name='line_name_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acct.Line_Price_t'),
        ),
        migrations.AlterField(
            model_name='application_t',
            name='local_agency_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local', to='acct.Agency_t'),
        ),
        migrations.AlterField(
            model_name='ref_price_t',
            name='line_price_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acct.Line_Price_t'),
        ),
        migrations.AlterField(
            model_name='settlement_t',
            name='application_t',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='acct.Application_t'),
        ),
        migrations.AlterField(
            model_name='settlement_t',
            name='pay_agency_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_agency', to='acct.Agency_t'),
        ),
        migrations.AlterField(
            model_name='settlement_t',
            name='rec_agency_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rec_agency', to='acct.Agency_t'),
        ),
        migrations.AlterField(
            model_name='tourist_t',
            name='application_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acct.Application_t'),
        ),
        migrations.AlterField(
            model_name='tourist_t',
            name='ref_price_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acct.Ref_Price_t'),
        ),
    ]
