# Generated by Django 2.1.1 on 2018-10-20 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0009_auto_20181020_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency_t',
            name='local_agency_fk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='djuser_t',
            name='local_agency_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='acct.Agency_t'),
        ),
        migrations.AlterField(
            model_name='line_price_t',
            name='local_agency_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='acct.Agency_t'),
        ),
        migrations.AlterField(
            model_name='ref_price_t',
            name='local_agency_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='acct.Agency_t'),
        ),
        migrations.AlterField(
            model_name='settlement_t',
            name='local_agency_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='acct.Agency_t'),
        ),
        migrations.AlterField(
            model_name='tourist_t',
            name='local_agency_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='acct.Agency_t'),
        ),
    ]
