# Generated by Django 2.1.1 on 2018-10-21 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0010_auto_20181020_1534'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agency_t',
            unique_together={('name', 'local_agency_fk')},
        ),
        migrations.AlterUniqueTogether(
            name='djuser_t',
            unique_together={('name', 'local_agency_fk')},
        ),
        migrations.AlterUniqueTogether(
            name='line_price_t',
            unique_together={('name', 'local_agency_fk')},
        ),
        migrations.AlterUniqueTogether(
            name='ref_price_t',
            unique_together={('kind', 'local_agency_fk', 'line_price_fk')},
        ),
    ]
