# Generated by Django 2.1.1 on 2019-02-17 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0003_auto_20190214_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='p_level',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='p_org',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='p_remark',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='user',
        ),
    ]
