# Generated by Django 2.1.1 on 2019-02-17 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0005_auto_20190217_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='delete_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='delete_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
