# Generated by Django 2.1.1 on 2019-02-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0007_auto_20190218_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='delete_time',
        ),
        migrations.AddField(
            model_name='employee',
            name='last_modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
