# Generated by Django 2.1.1 on 2019-03-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0008_auto_20190223_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
