# Generated by Django 2.1.1 on 2019-03-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0009_auto_20190305_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='remark',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
